#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 19 15:34:42 YEKT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
