#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Oct 12 23:32:31 YEKT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=10
shaderPack=\u00A76M\u00A7r+Bliss_v2.1.1_(Chocapic13_Shaders_edit).zip
