#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 10 16:32:05 YEKT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=\u00A7cH\u00A7r+ComplementaryUnbound_r5.5.1.zip
